[tool.black]
line-length = 100
target-version = ["py310"]
include = '\.pyi?$'
extend-exclude = '''
/(
  mmdetection
| code/GroundingDINO
| pretrained_ckpt
| outputs
| datasets
| weights
| .*venv
)/
'''
